## Originally created by EMBLmyGFF3

# -------------------------------------------
# Found in GFF3 columns
# GFF.parse() stores 'source' (2nd column), 'score' (6th column), and 'phase' (8th columns) as qualifiers of the corresponding SeqFeature
[source]
description = 'Typically this is the name of a piece of software, such as "Genescan" or a database name, such as "Genbank." In effect, the source is used to extend the feature ontology by adding a qualifier to the type creating a new composite type that is a subclass of the type in the type column.'
target = "note"
prefix = 'source:'

[score]
description = "The score of the feature, a floating point number. As in earlier versions of the format, the semantics of the score are ill-defined. It is strongly recommended that E-values be used for sequence similarity features, and that P-values be used for ab initio gene prediction features."
target = "score"

[phase]
description = 'For features of type "CDS", the phase indicates where the feature begins with reference to the reading frame. The phase is one of the integers 0, 1, or 2, indicating the number of bases that should be removed from the beginning of this feature to reach the first base of the next codon.'
target = "codon_start"

# --------------------------------------------
# Found in GFF3 attributes
[ID]
description = "Indicates the ID of the feature. IDs for each feature must be unique within the scope of the GFF file. In the case of discontinuous features (i.e. a single feature that exists over multiple genomic locations) the same ID may appear on multiple lines. All lines that share an ID collectively represent a single feature."
target = "note"
prefix = "ID:"

[Note]
description = "A free text note."
target = "note"

[Dbxref]
description = "A database cross reference."
target = "db_xref"

[gene_name]
description = 'The source is a free text qualifier intended to describe the algorithm or operating procedure that generated this feature. Typically this is the name of a piece of software, such as "Genescan" or a database name, such as "Genbank." In effect, the source is used to extend the feature ontology by adding a qualifier to the type creating a new composite type that is a subclass of the type in the type column.'
target = "gene"

[geneID]
description = "N/A"
target = "gene"

[description]
description = "N/A"
target = "product"

[eC_number]
description = "N/A"
target = "EC_number"

[locus_tag]
description = "This entry is to handle the locus tag prefix. DO NOT EDIT THIS."
target = "locus_tag"
prefix = "<dummy>"

[_Description]
description = "N/A"
target = "product"

